# backend/services/city_tags.py

CITY_TAGS = {
    "amsterdam": {
        "city_break",
        "canals",
        "museums",
        "art",
        "cycling",
        "walkable",
        "liberal",
        "nightlife",
        "cafes",
        "culture",
        "architecture",
        "cool",
        "spring_friendly",
        "autumn_friendly",
        "short_trip",
    },
    "lisbon": {
        "city_break",
        "history",
        "medieval",
        "old_town",
        "architecture",
        "nightlife",
        "beer",
        "romantic",
        "walkable",
        "affordable",
        "culture",
        "cool",
        "spring_friendly",
        "autumn_friendly",
        "short_trip",
    },
    "rome": {
        "history",
        "ancient",
        "landmarks",
        "architecture",
        "food",
        "cafes",
        "culture",
        "busy",
        "walkable",
        "romantic",
        "museums",
        "urban",
        "warm",
        "shoulder_season_best",
        "iconic",
    },
    "bordeaux": {
        "food_wine",
        "wine_region",
        "gastronomy",
        "relaxed",
        "elegant",
        "historic",
        "walkable",
        "cafes",
        "culture",
        "mild",
        "riverfront",
        "slow_travel",
        "spring_friendly",
        "autumn_friendly",
    },
    "sicily": {
        "beach",
        "island",
        "warm",
        "food",
        "seafood",
        "history",
        "ancient",
        "volcanoes",
        "nature",
        "scenic",
        "culture",
        "road_trip",
        "summer_friendly",
        "laid_back",
        "mediterranean",
    },
    "crete": {
        "beach",
        "island",
        "warm",
        "relaxed",
        "nature",
        "mountains",
        "hiking",
        "scenic",
        "history",
        "ancient",
        "food",
        "seafood",
        "slow_travel",
        "summer_friendly",
        "mediterranean",
    },
}

def cities_with_tag(tag: str):
    return [city for city, tags in CITY_TAGS.items() if tag in tags]

def cities_with_all_tags(required_tags: set[str]):
    return [
        city
        for city, tags in CITY_TAGS.items()
        if required_tags.issubset(tags)
    ]
